
all:
	gcc -g -c -I./include partition_cmd_line_test.c
	gcc -g -o test partition_cmd_line_test.o


##mk1:1_pointer_test.o
##gcc -std=c99 -c 1_pointer_test.c 
##gcc -     o 1_pointer_test 1_pointer_test.o 
###./1_pointer_test.exe
##chmod 77      7 ./1_pointer_test
##./1_pointer_test
        
