#===============================================================================
# Macro
#===============================================================================
CURRENT_DIR=$(shell pwd)
BIN=$(shell cd ~/;pwd)
PARSER_PATH=$(BIN)/.vim_runtime/ctags_parser

Q=@
BOOT_PATH=$(CURRENT_DIR)/../platform/bootloader
BOOT_BSP_PATH=$(CURRENT_DIR)/../platform/kernel_ext
KERNEL_PATH=$(CURRENT_DIR)/../platform/kernel/
BSP_PATH=$(CURRENT_DIR)/../platform/bsp/
MITRASTAR_APP_PATH=$(CURRENT_DIR)/sysapps/private/mitrastar
APP_PATH=$(CURRENT_DIR)/sysapps/private/third-party


#######################   function define begin  ######################
define GenCtagsingore
	echo "create .ctagsignore $(1)";
	@if [ ! -e $(1)/.ctagsignore  ];then \
		echo ".svn" >> $(1)/.ctagsignore; \
		echo ".git" >> $(1)/.ctagsignore; \
		echo "*.swap" >> $(1)/.ctagsignore; \
		echo "*.ts" >> $(1)/.ctagsignore; \
		echo "*.so.1" >> $(1)/.ctagsignore; \
		echo "*.so.2" >> $(1)/.ctagsignore; \
	fi;
endef


define GenerateHisiCtags
	echo "generate hisi rules";
	$(call GenCtagsingore,$(1))
	$(Q)cd $(1); \
	ctags --options=NONE --options=$(PARSER_PATH)/hisi.ctags --langmap=c:+.h --extras=+q --if0=no -o c_tags -R --exclude=@.ctagsignore;\
	/usr/bin/find $(1) -name "*.c" -o -name "*.h" -o -name "*.java" -o -name "*.cpp" -o -name "*.py" -o -name "*.sh" -o -name "*.lua" > $(1)/cs.files;\
	cscope -b -k -q $(1)/cs.files;
	@if [ -e $(1)/.previm  ];then \
		rm $(1)/.previm;\
	fi;
	echo "set tags=$(1)/c_tags " > $(1)/.previm 
endef


##  ctags --options=NONE --options=$(PARSER_PATH)/linux.ctags --langmap=c:+.h --extras=+q --if0=no -o c_tags -R --exclude=@.ctagsignore;
define GenerateLinuxCtags
	$(call GenCtagsingore,$(1))
	$(Q)cd $(1); \
	ctags --options=NONE --options=$(PARSER_PATH)/linux.ctags --langmap=c:+.h --extras=+q --if0=no -o c_tags -R --exclude=@.ctagsignore;\
	/usr/bin/find $(1) -name "*.c" -o -name "*.h" -o -name "*.java" -o -name "*.cpp" -o -name "*.py" -o -name "*.sh" -o -name "*.lua" > $(1)/cs.files;\
	cscope -b -k -q $(1)/cs.files;
	@if [ -e $(1)/.previm  ];then\
		rm $(1)/.previm;\
	fi;
	echo "set tags=$(1)/c_tags " > $(1)/.previm 
endef

##  ctags -R `pwd` is for full path, also for excluded file.
define GenMLDCtags
	$(call GenCtagsingore,$(1))
	$(Q)cd $(1); ctags --options=NONE --options=$(PARSER_PATH)/linux.ctags --langmap=c:+.h --extras=+q --if0=no -o c_tags --exclude=@.ctagsignore -R `pwd` ;\
	/usr/bin/find $(1) -name "*.c" -o -name "*.h" -o -name "*.java" -o -name "*.cpp" -o -name "*.py" -o -name "*.sh" -o -name "*.lua" > $(1)/cs.files;\
	cscope -b -k -q $(1)/cs.files;
	@if [ -e $(1)/.previm  ];then\
		rm $(1)/.previm;\
	fi;
	echo "set tags=$(1)/c_tags " > $(1)/.previm 
endef


define Clean
$(RM) $(1)/.previm ;\
	$(RM) $(1)/c_tags;\
	$(RM) $(1)/cscope* ;\
	$(RM) $(1)/cs.files ;\
	$(RM) $(1)/.ctagsignore;
endef
#######################   function define end   ######################


.PHONY:appdev_env
app_env:app_clean
	@if [ ! -e $(CURRENT_DIR)/sysapps/.ctagsignore ];then \
		echo "$(CURRENT_DIR)/sysapps/private/mitrastar/libplatform/realtek/960x/"  > $(CURRENT_DIR)/sysapps/.ctagsignore; \
		echo "$(CURRENT_DIR)/sysapps/public/others/openssl-0.9.7f/test/fips_aes_data/" >> $(CURRENT_DIR)/sysapps/.ctagsignore; \
		echo "$(CURRENT_DIR)/sysapps/private/third-party/mtk/7526G/apps/private/tclinux_builder/tclinux_allinone.swap"  >> $(CURRENT_DIR)/sysapps/.ctagsignore; \
		echo "$(CURRENT_DIR)/sysapps/private/third-party/mtk/7526G/apps/tclinux_builder/tclinux_allinone.swap"  >> $(CURRENT_DIR)/sysapps/.ctagsignore; \
		echo "$(CURRENT_DIR)/sysapps/private/third-party/mtk/7526G/apps/private/tclinux_builder"  >> $(CURRENT_DIR)/sysapps/.ctagsignore; \
		echo "svn" >> $(CURRENT_DIR)/sysapps/.ctagsignore; \
	fi;
	$(call GenerateLinuxCtags,$(APP_PATH))


.PHONY:app_clean
app_clean:
	$(call Clean,$(APP_PATH))


.PHONY:des_clean
	des_clean: boot_clean kernel_clean bsp_clean


.PHONY:boot_env
boot_env:boot_clean
	@if [ ! -e $(BOOT_PATH)/.ctagsignore ];then \
		echo "svn" > $(BOOT_PATH)/.ctagsignore; \
		echo "hisi.ctags" >> $(BOOT_PATH)/.ctagsignore; \
		echo "uboot/tcboot_MRD.bin.swap" >> $(BOOT_PATH)/.ctagsignore; \
		echo "tcboot_MRD.bin.swap" >> $(BOOT_PATH)/.ctagsignore; \
		echo "uboot/bootram/*" >> $(BOOT_PATH)/.ctagsignore; \
	fi;
	@if [ ! -e $(BOOT_BSP_PATH)/.ctagsignore ];then \
		echo "svn" > $(BOOT_BSP_PATH)/.ctagsignore; \
		echo "hisi.ctags" >> $(BOOT_BSP_PATH)/.ctagsignore; \
	fi;
	$(call GenerateLinuxCtags,$(BOOT_PATH))
	$(call GenerateLinuxCtags,$(BOOT_BSP_PATH))


.PHONY:boot_clean
boot_clean:
	$(call Clean,$(BOOT_PATH))


.PHONY:kernel_env
kernel_env:kernel_clean 
	@if [ ! -e $(KERNEL_PATH)/.ctagsignore ];then \
		echo "svn" > $(KERNEL_PATH)/.ctagsignore; \
	fi;
	$(call GenerateLinuxCtags,$(KERNEL_PATH))


.PHONY:kernel_clean
kernel_clean:
	$(call Clean,$(KERNEL_PATH))


.PHONY:bsp_env
bsp_env: bsp_clean
	@if [ ! -e $(BSP_PATH)/.ctagsignore ];then \
		echo "svn" > $(BSP_PATH)/.ctagsignore; \
	fi;	
	$(call GenerateLinuxCtags,$(BSP_PATH))


.PHONY:bsp_clean
bsp_clean:
	$(call Clean,$(BSP_PATH))


.PHONY:app_zyclip_env
app_zyclip_env:app_zyclip_clean
	@if [ ! -e $(MITRASTAR_APP_PATH)/.ctagsignore  ];then \
 		echo $(MITRASTAR_APP_PATH)"/libCmd/BROADCOM/* "  > $(MITRASTAR_APP_PATH)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/libcmd/CORTINA/* "  >> $(mitrastar_app_path)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/libCmd/REALTEK/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/libCmd/BROADCOM/* "  > $(MITRASTAR_APP_PATH)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/libcmd/CORTINA/* "  >> $(mitrastar_app_path)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/libCmd/REALTEK/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/libwrappercommon/BROADCOM/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/libwrappercommon/CORTINA/* "  >> $(mitrastar_app_path)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/libwrappercommon/REALTEK/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/libledctl/BROADCOM/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/libledctl/CORTINA/* "  >> $(mitrastar_app_path)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/libledctl/REALTEK/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/libboardaccess/BROADCOM/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/libboardaccess/CORTINA/* "  >> $(mitrastar_app_path)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/libboardaccess/REALTEK/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/librdmcommon/BROADCOM/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/librdmcommon/CORTINA/* "  >> $(mitrastar_app_path)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/librdmcommon/REALTEK/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/lnkdetection/BROADCOM/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/lnkdetection/CORTINA/* "  >> $(mitrastar_app_path)/.ctagsignore; \
		echo $(MITRASTAR_APP_PATH)"/lnkdetection/REALTEK/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
	fi;
	$(call GenMLDCtags,$(MITRASTAR_APP_PATH))

# 		echo $(MITRASTAR_APP_PATH)"/libCmd/BROADCOM/* "  > $(MITRASTAR_APP_PATH)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/libcmd/CORTINA/* "  >> $(mitrastar_app_path)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/libCmd/REALTEK/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/libCmd/BROADCOM/* "  > $(MITRASTAR_APP_PATH)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/libcmd/CORTINA/* "  >> $(mitrastar_app_path)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/libCmd/REALTEK/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/libwrappercommon/BROADCOM/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/libwrappercommon/CORTINA/* "  >> $(mitrastar_app_path)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/libwrappercommon/REALTEK/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/libledctl/BROADCOM/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/libledctl/CORTINA/* "  >> $(mitrastar_app_path)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/libledctl/REALTEK/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/libboardaccess/BROADCOM/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/libboardaccess/CORTINA/* "  >> $(mitrastar_app_path)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/libboardaccess/REALTEK/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/librdmcommon/BROADCOM/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/librdmcommon/CORTINA/* "  >> $(mitrastar_app_path)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/librdmcommon/REALTEK/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/lnkdetection/BROADCOM/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/lnkdetection/CORTINA/* "  >> $(mitrastar_app_path)/.ctagsignore; \
#		echo $(MITRASTAR_APP_PATH)"/lnkdetection/REALTEK/* "  >> $(MITRASTAR_APP_PATH)/.ctagsignore; \


.PHONY:app_zyclip_clean
app_zyclip_clean:
	$(call Clean,$(MITRASTAR_APP_PATH))
 
